// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: adam_control.proto

#include "adam_control.pb.h"
#include "adam_control.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace adam_control {

static const char* RobotControl_method_names[] = {
  "/adam_control.RobotControl/SetMode",
  "/adam_control.RobotControl/SetStandMotion",
  "/adam_control.RobotControl/SetStandCarryBox",
  "/adam_control.RobotControl/SetStandAction",
  "/adam_control.RobotControl/SetStandDynamic",
  "/adam_control.RobotControl/SetSpeed",
  "/adam_control.RobotControl/AutoUnigaitCOM",
  "/adam_control.RobotControl/SetErrorClear",
  "/adam_control.RobotControl/GetStandList",
  "/adam_control.RobotControl/GetRobotState",
  "/adam_control.RobotControl/CloseProgram",
  "/adam_control.RobotControl/SetControlMode",
  "/adam_control.RobotControl/GetControlState",
};

std::unique_ptr< RobotControl::Stub> RobotControl::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RobotControl::Stub> stub(new RobotControl::Stub(channel, options));
  return stub;
}

RobotControl::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetMode_(RobotControl_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetStandMotion_(RobotControl_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetStandCarryBox_(RobotControl_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetStandAction_(RobotControl_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetStandDynamic_(RobotControl_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSpeed_(RobotControl_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AutoUnigaitCOM_(RobotControl_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetErrorClear_(RobotControl_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStandList_(RobotControl_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRobotState_(RobotControl_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CloseProgram_(RobotControl_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetControlMode_(RobotControl_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetControlState_(RobotControl_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RobotControl::Stub::SetMode(::grpc::ClientContext* context, const ::adam_control::SetModeRequest& request, ::adam_control::SetModeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetModeRequest, ::adam_control::SetModeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetMode_, context, request, response);
}

void RobotControl::Stub::async::SetMode(::grpc::ClientContext* context, const ::adam_control::SetModeRequest* request, ::adam_control::SetModeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetModeRequest, ::adam_control::SetModeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetMode_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetMode(::grpc::ClientContext* context, const ::adam_control::SetModeRequest* request, ::adam_control::SetModeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetMode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetModeResponse>* RobotControl::Stub::PrepareAsyncSetModeRaw(::grpc::ClientContext* context, const ::adam_control::SetModeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetModeResponse, ::adam_control::SetModeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetMode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetModeResponse>* RobotControl::Stub::AsyncSetModeRaw(::grpc::ClientContext* context, const ::adam_control::SetModeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetModeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::SetStandMotion(::grpc::ClientContext* context, const ::adam_control::SetStandMotionRequest& request, ::adam_control::SetStandMotionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetStandMotionRequest, ::adam_control::SetStandMotionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetStandMotion_, context, request, response);
}

void RobotControl::Stub::async::SetStandMotion(::grpc::ClientContext* context, const ::adam_control::SetStandMotionRequest* request, ::adam_control::SetStandMotionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetStandMotionRequest, ::adam_control::SetStandMotionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandMotion_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetStandMotion(::grpc::ClientContext* context, const ::adam_control::SetStandMotionRequest* request, ::adam_control::SetStandMotionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandMotion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetStandMotionResponse>* RobotControl::Stub::PrepareAsyncSetStandMotionRaw(::grpc::ClientContext* context, const ::adam_control::SetStandMotionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetStandMotionResponse, ::adam_control::SetStandMotionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetStandMotion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetStandMotionResponse>* RobotControl::Stub::AsyncSetStandMotionRaw(::grpc::ClientContext* context, const ::adam_control::SetStandMotionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetStandMotionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::SetStandCarryBox(::grpc::ClientContext* context, const ::adam_control::SetCarryBoxRequest& request, ::adam_control::SetCarryBoxResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetCarryBoxRequest, ::adam_control::SetCarryBoxResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetStandCarryBox_, context, request, response);
}

void RobotControl::Stub::async::SetStandCarryBox(::grpc::ClientContext* context, const ::adam_control::SetCarryBoxRequest* request, ::adam_control::SetCarryBoxResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetCarryBoxRequest, ::adam_control::SetCarryBoxResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandCarryBox_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetStandCarryBox(::grpc::ClientContext* context, const ::adam_control::SetCarryBoxRequest* request, ::adam_control::SetCarryBoxResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandCarryBox_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetCarryBoxResponse>* RobotControl::Stub::PrepareAsyncSetStandCarryBoxRaw(::grpc::ClientContext* context, const ::adam_control::SetCarryBoxRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetCarryBoxResponse, ::adam_control::SetCarryBoxRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetStandCarryBox_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetCarryBoxResponse>* RobotControl::Stub::AsyncSetStandCarryBoxRaw(::grpc::ClientContext* context, const ::adam_control::SetCarryBoxRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetStandCarryBoxRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::SetStandAction(::grpc::ClientContext* context, const ::adam_control::SetActionRequest& request, ::adam_control::SetActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetActionRequest, ::adam_control::SetActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetStandAction_, context, request, response);
}

void RobotControl::Stub::async::SetStandAction(::grpc::ClientContext* context, const ::adam_control::SetActionRequest* request, ::adam_control::SetActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetActionRequest, ::adam_control::SetActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandAction_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetStandAction(::grpc::ClientContext* context, const ::adam_control::SetActionRequest* request, ::adam_control::SetActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandAction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetActionResponse>* RobotControl::Stub::PrepareAsyncSetStandActionRaw(::grpc::ClientContext* context, const ::adam_control::SetActionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetActionResponse, ::adam_control::SetActionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetStandAction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetActionResponse>* RobotControl::Stub::AsyncSetStandActionRaw(::grpc::ClientContext* context, const ::adam_control::SetActionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetStandActionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::SetStandDynamic(::grpc::ClientContext* context, const ::adam_control::SetDynamicStandRequest& request, ::adam_control::SetDynamicStandResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetDynamicStandRequest, ::adam_control::SetDynamicStandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetStandDynamic_, context, request, response);
}

void RobotControl::Stub::async::SetStandDynamic(::grpc::ClientContext* context, const ::adam_control::SetDynamicStandRequest* request, ::adam_control::SetDynamicStandResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetDynamicStandRequest, ::adam_control::SetDynamicStandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandDynamic_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetStandDynamic(::grpc::ClientContext* context, const ::adam_control::SetDynamicStandRequest* request, ::adam_control::SetDynamicStandResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetStandDynamic_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetDynamicStandResponse>* RobotControl::Stub::PrepareAsyncSetStandDynamicRaw(::grpc::ClientContext* context, const ::adam_control::SetDynamicStandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetDynamicStandResponse, ::adam_control::SetDynamicStandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetStandDynamic_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetDynamicStandResponse>* RobotControl::Stub::AsyncSetStandDynamicRaw(::grpc::ClientContext* context, const ::adam_control::SetDynamicStandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetStandDynamicRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::SetSpeed(::grpc::ClientContext* context, const ::adam_control::SetSpeedRequest& request, ::adam_control::SetSpeedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetSpeedRequest, ::adam_control::SetSpeedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetSpeed_, context, request, response);
}

void RobotControl::Stub::async::SetSpeed(::grpc::ClientContext* context, const ::adam_control::SetSpeedRequest* request, ::adam_control::SetSpeedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetSpeedRequest, ::adam_control::SetSpeedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSpeed_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetSpeed(::grpc::ClientContext* context, const ::adam_control::SetSpeedRequest* request, ::adam_control::SetSpeedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSpeed_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetSpeedResponse>* RobotControl::Stub::PrepareAsyncSetSpeedRaw(::grpc::ClientContext* context, const ::adam_control::SetSpeedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetSpeedResponse, ::adam_control::SetSpeedRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetSpeed_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetSpeedResponse>* RobotControl::Stub::AsyncSetSpeedRaw(::grpc::ClientContext* context, const ::adam_control::SetSpeedRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetSpeedRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::AutoUnigaitCOM(::grpc::ClientContext* context, const ::adam_control::SetUnigaitCOMRequest& request, ::adam_control::SetUnigaitCOMResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetUnigaitCOMRequest, ::adam_control::SetUnigaitCOMResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AutoUnigaitCOM_, context, request, response);
}

void RobotControl::Stub::async::AutoUnigaitCOM(::grpc::ClientContext* context, const ::adam_control::SetUnigaitCOMRequest* request, ::adam_control::SetUnigaitCOMResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetUnigaitCOMRequest, ::adam_control::SetUnigaitCOMResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AutoUnigaitCOM_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::AutoUnigaitCOM(::grpc::ClientContext* context, const ::adam_control::SetUnigaitCOMRequest* request, ::adam_control::SetUnigaitCOMResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AutoUnigaitCOM_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetUnigaitCOMResponse>* RobotControl::Stub::PrepareAsyncAutoUnigaitCOMRaw(::grpc::ClientContext* context, const ::adam_control::SetUnigaitCOMRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetUnigaitCOMResponse, ::adam_control::SetUnigaitCOMRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AutoUnigaitCOM_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetUnigaitCOMResponse>* RobotControl::Stub::AsyncAutoUnigaitCOMRaw(::grpc::ClientContext* context, const ::adam_control::SetUnigaitCOMRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAutoUnigaitCOMRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::SetErrorClear(::grpc::ClientContext* context, const ::adam_control::SetErrorClearRequest& request, ::adam_control::SetErrorClearResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetErrorClearRequest, ::adam_control::SetErrorClearResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetErrorClear_, context, request, response);
}

void RobotControl::Stub::async::SetErrorClear(::grpc::ClientContext* context, const ::adam_control::SetErrorClearRequest* request, ::adam_control::SetErrorClearResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetErrorClearRequest, ::adam_control::SetErrorClearResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetErrorClear_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetErrorClear(::grpc::ClientContext* context, const ::adam_control::SetErrorClearRequest* request, ::adam_control::SetErrorClearResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetErrorClear_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetErrorClearResponse>* RobotControl::Stub::PrepareAsyncSetErrorClearRaw(::grpc::ClientContext* context, const ::adam_control::SetErrorClearRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetErrorClearResponse, ::adam_control::SetErrorClearRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetErrorClear_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetErrorClearResponse>* RobotControl::Stub::AsyncSetErrorClearRaw(::grpc::ClientContext* context, const ::adam_control::SetErrorClearRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetErrorClearRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::GetStandList(::grpc::ClientContext* context, const ::adam_control::GetStandListRequest& request, ::adam_control::GetStandListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::GetStandListRequest, ::adam_control::GetStandListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStandList_, context, request, response);
}

void RobotControl::Stub::async::GetStandList(::grpc::ClientContext* context, const ::adam_control::GetStandListRequest* request, ::adam_control::GetStandListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::GetStandListRequest, ::adam_control::GetStandListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStandList_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::GetStandList(::grpc::ClientContext* context, const ::adam_control::GetStandListRequest* request, ::adam_control::GetStandListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStandList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::GetStandListResponse>* RobotControl::Stub::PrepareAsyncGetStandListRaw(::grpc::ClientContext* context, const ::adam_control::GetStandListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::GetStandListResponse, ::adam_control::GetStandListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStandList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::GetStandListResponse>* RobotControl::Stub::AsyncGetStandListRaw(::grpc::ClientContext* context, const ::adam_control::GetStandListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStandListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::GetRobotState(::grpc::ClientContext* context, const ::adam_control::GetRobotStateRequest& request, ::adam_control::GetRobotStateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::GetRobotStateRequest, ::adam_control::GetRobotStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRobotState_, context, request, response);
}

void RobotControl::Stub::async::GetRobotState(::grpc::ClientContext* context, const ::adam_control::GetRobotStateRequest* request, ::adam_control::GetRobotStateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::GetRobotStateRequest, ::adam_control::GetRobotStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRobotState_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::GetRobotState(::grpc::ClientContext* context, const ::adam_control::GetRobotStateRequest* request, ::adam_control::GetRobotStateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRobotState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::GetRobotStateResponse>* RobotControl::Stub::PrepareAsyncGetRobotStateRaw(::grpc::ClientContext* context, const ::adam_control::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::GetRobotStateResponse, ::adam_control::GetRobotStateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRobotState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::GetRobotStateResponse>* RobotControl::Stub::AsyncGetRobotStateRaw(::grpc::ClientContext* context, const ::adam_control::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRobotStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::CloseProgram(::grpc::ClientContext* context, const ::adam_control::CloseProgramRequest& request, ::adam_control::CloseProgramResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::CloseProgramRequest, ::adam_control::CloseProgramResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CloseProgram_, context, request, response);
}

void RobotControl::Stub::async::CloseProgram(::grpc::ClientContext* context, const ::adam_control::CloseProgramRequest* request, ::adam_control::CloseProgramResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::CloseProgramRequest, ::adam_control::CloseProgramResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseProgram_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::CloseProgram(::grpc::ClientContext* context, const ::adam_control::CloseProgramRequest* request, ::adam_control::CloseProgramResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseProgram_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::CloseProgramResponse>* RobotControl::Stub::PrepareAsyncCloseProgramRaw(::grpc::ClientContext* context, const ::adam_control::CloseProgramRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::CloseProgramResponse, ::adam_control::CloseProgramRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CloseProgram_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::CloseProgramResponse>* RobotControl::Stub::AsyncCloseProgramRaw(::grpc::ClientContext* context, const ::adam_control::CloseProgramRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCloseProgramRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::SetControlMode(::grpc::ClientContext* context, const ::adam_control::SetControlModeRequest& request, ::adam_control::SetControlModeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::SetControlModeRequest, ::adam_control::SetControlModeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetControlMode_, context, request, response);
}

void RobotControl::Stub::async::SetControlMode(::grpc::ClientContext* context, const ::adam_control::SetControlModeRequest* request, ::adam_control::SetControlModeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::SetControlModeRequest, ::adam_control::SetControlModeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetControlMode_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::SetControlMode(::grpc::ClientContext* context, const ::adam_control::SetControlModeRequest* request, ::adam_control::SetControlModeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetControlMode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetControlModeResponse>* RobotControl::Stub::PrepareAsyncSetControlModeRaw(::grpc::ClientContext* context, const ::adam_control::SetControlModeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::SetControlModeResponse, ::adam_control::SetControlModeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetControlMode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::SetControlModeResponse>* RobotControl::Stub::AsyncSetControlModeRaw(::grpc::ClientContext* context, const ::adam_control::SetControlModeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetControlModeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotControl::Stub::GetControlState(::grpc::ClientContext* context, const ::adam_control::GetControlStateRequest& request, ::adam_control::GetControlStateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::adam_control::GetControlStateRequest, ::adam_control::GetControlStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetControlState_, context, request, response);
}

void RobotControl::Stub::async::GetControlState(::grpc::ClientContext* context, const ::adam_control::GetControlStateRequest* request, ::adam_control::GetControlStateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::adam_control::GetControlStateRequest, ::adam_control::GetControlStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetControlState_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::GetControlState(::grpc::ClientContext* context, const ::adam_control::GetControlStateRequest* request, ::adam_control::GetControlStateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetControlState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::adam_control::GetControlStateResponse>* RobotControl::Stub::PrepareAsyncGetControlStateRaw(::grpc::ClientContext* context, const ::adam_control::GetControlStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::adam_control::GetControlStateResponse, ::adam_control::GetControlStateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetControlState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::adam_control::GetControlStateResponse>* RobotControl::Stub::AsyncGetControlStateRaw(::grpc::ClientContext* context, const ::adam_control::GetControlStateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetControlStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

RobotControl::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetModeRequest, ::adam_control::SetModeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetModeRequest* req,
             ::adam_control::SetModeResponse* resp) {
               return service->SetMode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetStandMotionRequest, ::adam_control::SetStandMotionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetStandMotionRequest* req,
             ::adam_control::SetStandMotionResponse* resp) {
               return service->SetStandMotion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetCarryBoxRequest, ::adam_control::SetCarryBoxResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetCarryBoxRequest* req,
             ::adam_control::SetCarryBoxResponse* resp) {
               return service->SetStandCarryBox(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetActionRequest, ::adam_control::SetActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetActionRequest* req,
             ::adam_control::SetActionResponse* resp) {
               return service->SetStandAction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetDynamicStandRequest, ::adam_control::SetDynamicStandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetDynamicStandRequest* req,
             ::adam_control::SetDynamicStandResponse* resp) {
               return service->SetStandDynamic(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetSpeedRequest, ::adam_control::SetSpeedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetSpeedRequest* req,
             ::adam_control::SetSpeedResponse* resp) {
               return service->SetSpeed(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetUnigaitCOMRequest, ::adam_control::SetUnigaitCOMResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetUnigaitCOMRequest* req,
             ::adam_control::SetUnigaitCOMResponse* resp) {
               return service->AutoUnigaitCOM(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetErrorClearRequest, ::adam_control::SetErrorClearResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetErrorClearRequest* req,
             ::adam_control::SetErrorClearResponse* resp) {
               return service->SetErrorClear(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::GetStandListRequest, ::adam_control::GetStandListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::GetStandListRequest* req,
             ::adam_control::GetStandListResponse* resp) {
               return service->GetStandList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::GetRobotStateRequest, ::adam_control::GetRobotStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::GetRobotStateRequest* req,
             ::adam_control::GetRobotStateResponse* resp) {
               return service->GetRobotState(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::CloseProgramRequest, ::adam_control::CloseProgramResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::CloseProgramRequest* req,
             ::adam_control::CloseProgramResponse* resp) {
               return service->CloseProgram(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::SetControlModeRequest, ::adam_control::SetControlModeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::SetControlModeRequest* req,
             ::adam_control::SetControlModeResponse* resp) {
               return service->SetControlMode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::adam_control::GetControlStateRequest, ::adam_control::GetControlStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::adam_control::GetControlStateRequest* req,
             ::adam_control::GetControlStateResponse* resp) {
               return service->GetControlState(ctx, req, resp);
             }, this)));
}

RobotControl::Service::~Service() {
}

::grpc::Status RobotControl::Service::SetMode(::grpc::ServerContext* context, const ::adam_control::SetModeRequest* request, ::adam_control::SetModeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::SetStandMotion(::grpc::ServerContext* context, const ::adam_control::SetStandMotionRequest* request, ::adam_control::SetStandMotionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::SetStandCarryBox(::grpc::ServerContext* context, const ::adam_control::SetCarryBoxRequest* request, ::adam_control::SetCarryBoxResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::SetStandAction(::grpc::ServerContext* context, const ::adam_control::SetActionRequest* request, ::adam_control::SetActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::SetStandDynamic(::grpc::ServerContext* context, const ::adam_control::SetDynamicStandRequest* request, ::adam_control::SetDynamicStandResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::SetSpeed(::grpc::ServerContext* context, const ::adam_control::SetSpeedRequest* request, ::adam_control::SetSpeedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::AutoUnigaitCOM(::grpc::ServerContext* context, const ::adam_control::SetUnigaitCOMRequest* request, ::adam_control::SetUnigaitCOMResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::SetErrorClear(::grpc::ServerContext* context, const ::adam_control::SetErrorClearRequest* request, ::adam_control::SetErrorClearResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::GetStandList(::grpc::ServerContext* context, const ::adam_control::GetStandListRequest* request, ::adam_control::GetStandListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::GetRobotState(::grpc::ServerContext* context, const ::adam_control::GetRobotStateRequest* request, ::adam_control::GetRobotStateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::CloseProgram(::grpc::ServerContext* context, const ::adam_control::CloseProgramRequest* request, ::adam_control::CloseProgramResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::SetControlMode(::grpc::ServerContext* context, const ::adam_control::SetControlModeRequest* request, ::adam_control::SetControlModeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotControl::Service::GetControlState(::grpc::ServerContext* context, const ::adam_control::GetControlStateRequest* request, ::adam_control::GetControlStateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace adam_control

