# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adam_control_pb2 as adam__control__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in adam_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControlStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMode = channel.unary_unary(
                '/adam_control.RobotControl/SetMode',
                request_serializer=adam__control__pb2.SetModeRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.SetStandMotion = channel.unary_unary(
                '/adam_control.RobotControl/SetStandMotion',
                request_serializer=adam__control__pb2.SetStandMotionRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetStandMotionResponse.FromString,
                _registered_method=True)
        self.SetStandCarryBox = channel.unary_unary(
                '/adam_control.RobotControl/SetStandCarryBox',
                request_serializer=adam__control__pb2.SetCarryBoxRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetCarryBoxResponse.FromString,
                _registered_method=True)
        self.SetStandAction = channel.unary_unary(
                '/adam_control.RobotControl/SetStandAction',
                request_serializer=adam__control__pb2.SetActionRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetActionResponse.FromString,
                _registered_method=True)
        self.SetStandDynamic = channel.unary_unary(
                '/adam_control.RobotControl/SetStandDynamic',
                request_serializer=adam__control__pb2.SetDynamicStandRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetDynamicStandResponse.FromString,
                _registered_method=True)
        self.SetSpeed = channel.unary_unary(
                '/adam_control.RobotControl/SetSpeed',
                request_serializer=adam__control__pb2.SetSpeedRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetSpeedResponse.FromString,
                _registered_method=True)
        self.AutoUnigaitCOM = channel.unary_unary(
                '/adam_control.RobotControl/AutoUnigaitCOM',
                request_serializer=adam__control__pb2.SetUnigaitCOMRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetUnigaitCOMResponse.FromString,
                _registered_method=True)
        self.SetErrorClear = channel.unary_unary(
                '/adam_control.RobotControl/SetErrorClear',
                request_serializer=adam__control__pb2.SetErrorClearRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetErrorClearResponse.FromString,
                _registered_method=True)
        self.GetStandList = channel.unary_unary(
                '/adam_control.RobotControl/GetStandList',
                request_serializer=adam__control__pb2.GetStandListRequest.SerializeToString,
                response_deserializer=adam__control__pb2.GetStandListResponse.FromString,
                _registered_method=True)
        self.GetRobotState = channel.unary_unary(
                '/adam_control.RobotControl/GetRobotState',
                request_serializer=adam__control__pb2.GetRobotStateRequest.SerializeToString,
                response_deserializer=adam__control__pb2.GetRobotStateResponse.FromString,
                _registered_method=True)
        self.CloseProgram = channel.unary_unary(
                '/adam_control.RobotControl/CloseProgram',
                request_serializer=adam__control__pb2.CloseProgramRequest.SerializeToString,
                response_deserializer=adam__control__pb2.CloseProgramResponse.FromString,
                _registered_method=True)
        self.SetControlMode = channel.unary_unary(
                '/adam_control.RobotControl/SetControlMode',
                request_serializer=adam__control__pb2.SetControlModeRequest.SerializeToString,
                response_deserializer=adam__control__pb2.SetControlModeResponse.FromString,
                _registered_method=True)
        self.GetControlState = channel.unary_unary(
                '/adam_control.RobotControl/GetControlState',
                request_serializer=adam__control__pb2.GetControlStateRequest.SerializeToString,
                response_deserializer=adam__control__pb2.GetControlStateResponse.FromString,
                _registered_method=True)


class RobotControlServicer(object):
    """Define the service
    """

    def SetMode(self, request, context):
        """Set robot mode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStandMotion(self, request, context):
        """In Stand mode - execute predefined motion capture actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStandCarryBox(self, request, context):
        """In Stand mode - execute box-carrying actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStandAction(self, request, context):
        """In Stand mode - execute posture control and squat height control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStandDynamic(self, request, context):
        """In Stand mode - adjust dynamic balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeed(self, request, context):
        """In Walk and Run modes - set speed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoUnigaitCOM(self, request, context):
        """In Walk and Run modes - COM X-direction offset balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetErrorClear(self, request, context):
        """Error reset without restarting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStandList(self, request, context):
        """Get robot mode list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotState(self, request, context):
        """Get current executable state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseProgram(self, request, context):
        """Close the program
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControlMode(self, request, context):
        """控制范式切换：Traditional(0) / RL(1)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlState(self, request, context):
        """读取当前控制范式状态（DDS rt/control_mode_state 反馈）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=adam__control__pb2.SetModeRequest.FromString,
                    response_serializer=adam__control__pb2.SetModeResponse.SerializeToString,
            ),
            'SetStandMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStandMotion,
                    request_deserializer=adam__control__pb2.SetStandMotionRequest.FromString,
                    response_serializer=adam__control__pb2.SetStandMotionResponse.SerializeToString,
            ),
            'SetStandCarryBox': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStandCarryBox,
                    request_deserializer=adam__control__pb2.SetCarryBoxRequest.FromString,
                    response_serializer=adam__control__pb2.SetCarryBoxResponse.SerializeToString,
            ),
            'SetStandAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStandAction,
                    request_deserializer=adam__control__pb2.SetActionRequest.FromString,
                    response_serializer=adam__control__pb2.SetActionResponse.SerializeToString,
            ),
            'SetStandDynamic': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStandDynamic,
                    request_deserializer=adam__control__pb2.SetDynamicStandRequest.FromString,
                    response_serializer=adam__control__pb2.SetDynamicStandResponse.SerializeToString,
            ),
            'SetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeed,
                    request_deserializer=adam__control__pb2.SetSpeedRequest.FromString,
                    response_serializer=adam__control__pb2.SetSpeedResponse.SerializeToString,
            ),
            'AutoUnigaitCOM': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoUnigaitCOM,
                    request_deserializer=adam__control__pb2.SetUnigaitCOMRequest.FromString,
                    response_serializer=adam__control__pb2.SetUnigaitCOMResponse.SerializeToString,
            ),
            'SetErrorClear': grpc.unary_unary_rpc_method_handler(
                    servicer.SetErrorClear,
                    request_deserializer=adam__control__pb2.SetErrorClearRequest.FromString,
                    response_serializer=adam__control__pb2.SetErrorClearResponse.SerializeToString,
            ),
            'GetStandList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStandList,
                    request_deserializer=adam__control__pb2.GetStandListRequest.FromString,
                    response_serializer=adam__control__pb2.GetStandListResponse.SerializeToString,
            ),
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=adam__control__pb2.GetRobotStateRequest.FromString,
                    response_serializer=adam__control__pb2.GetRobotStateResponse.SerializeToString,
            ),
            'CloseProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseProgram,
                    request_deserializer=adam__control__pb2.CloseProgramRequest.FromString,
                    response_serializer=adam__control__pb2.CloseProgramResponse.SerializeToString,
            ),
            'SetControlMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControlMode,
                    request_deserializer=adam__control__pb2.SetControlModeRequest.FromString,
                    response_serializer=adam__control__pb2.SetControlModeResponse.SerializeToString,
            ),
            'GetControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlState,
                    request_deserializer=adam__control__pb2.GetControlStateRequest.FromString,
                    response_serializer=adam__control__pb2.GetControlStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adam_control.RobotControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adam_control.RobotControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotControl(object):
    """Define the service
    """

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetMode',
            adam__control__pb2.SetModeRequest.SerializeToString,
            adam__control__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStandMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetStandMotion',
            adam__control__pb2.SetStandMotionRequest.SerializeToString,
            adam__control__pb2.SetStandMotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStandCarryBox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetStandCarryBox',
            adam__control__pb2.SetCarryBoxRequest.SerializeToString,
            adam__control__pb2.SetCarryBoxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStandAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetStandAction',
            adam__control__pb2.SetActionRequest.SerializeToString,
            adam__control__pb2.SetActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStandDynamic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetStandDynamic',
            adam__control__pb2.SetDynamicStandRequest.SerializeToString,
            adam__control__pb2.SetDynamicStandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetSpeed',
            adam__control__pb2.SetSpeedRequest.SerializeToString,
            adam__control__pb2.SetSpeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoUnigaitCOM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/AutoUnigaitCOM',
            adam__control__pb2.SetUnigaitCOMRequest.SerializeToString,
            adam__control__pb2.SetUnigaitCOMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetErrorClear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetErrorClear',
            adam__control__pb2.SetErrorClearRequest.SerializeToString,
            adam__control__pb2.SetErrorClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStandList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/GetStandList',
            adam__control__pb2.GetStandListRequest.SerializeToString,
            adam__control__pb2.GetStandListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/GetRobotState',
            adam__control__pb2.GetRobotStateRequest.SerializeToString,
            adam__control__pb2.GetRobotStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/CloseProgram',
            adam__control__pb2.CloseProgramRequest.SerializeToString,
            adam__control__pb2.CloseProgramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControlMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/SetControlMode',
            adam__control__pb2.SetControlModeRequest.SerializeToString,
            adam__control__pb2.SetControlModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam_control.RobotControl/GetControlState',
            adam__control__pb2.GetControlStateRequest.SerializeToString,
            adam__control__pb2.GetControlStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
